### ISSUE TITLE
Error with 0.3.1

### ISSUE THREAD

**Issue by luismmontielg** [dziegler/django-cachebot#4]
I get error 'CacheClass' object has no attribute 'append' on several places, any idea on this?, Im using django 1.2.5

**Comment by dziegler** [comment]
Oops, are you using the dummy cache backend by any chance?

**Comment by luismmontielg** [comment]
nope , Im using the memchached one

**Comment by dziegler** [comment]
Is your backend path correct? 

CACHE_BACKEND = 'cachebot.backends.memcached://127.0.0.1:11211/?timeout=0'

**Comment by luismmontielg** [comment]
oh, I dont think it is

CACHE_BACKEND = 'memcached://unix:/home/luis/memcached.sock'

Thanks, I'll change that on the code, and test, its just that I cant do it right now
